import React, { useState } from 'react';
import { SetupConfig, DesktopEnvironment, DisplayProtocol, HardwareAccel, DistroType } from '../types';
import { Sparkles, Terminal, Copy, Check, Download, Cpu, Shield, HardDrive, Volume2, Box } from 'lucide-react';

interface SetupWizardProps {
  config: SetupConfig;
  setConfig: React.Dispatch<React.SetStateAction<SetupConfig>>;
  onExportScript: () => void;
}

export const SetupWizard: React.FC<SetupWizardProps> = ({ config, setConfig, onExportScript }) => {
  const [copiedScript, setCopiedScript] = useState(false);

  const generateBashScript = () => {
    return `#!/usr/bin/env bash
# ========================================================
# Termux Desktop Automated Setup Script
# Generated by Termux Desktop Web Studio
# Config: DE=${config.de.toUpperCase()} | Protocol=${config.protocol} | HWA=${config.hwa} | Distro=${config.distro}
# ========================================================

set -e

echo "[*] Updating Termux packages..."
pkg update -y && pkg upgrade -y

echo "[*] Installing essential tools (curl, wget, git, pulseaudio)..."
pkg install -y wget curl git pulseaudio x11-repo tur-repo

${config.protocol === 'termux-x11' ? `
echo "[*] Installing Termux-X11 package..."
pkg install -y termux-x11-nightly
` : ''}

${config.protocol === 'vnc' ? `
echo "[*] Installing TigerVNC..."
pkg install -y tigervnc
` : ''}

${config.hwa === 'adreno' ? `
echo "[*] Configuring Adreno Turnip + Zink Hardware Acceleration..."
pkg install -y mesa-vulkan-icd-turnip zink
export MESA_LOADER_DRIVER_OVERRIDE=zink
export GALLIUM_DRIVER=zink
` : ''}

${config.distro !== 'ubuntu' && config.distro !== 'debian' ? `
echo "[*] Installing PRoot Distro (${config.distro})..."
pkg install -y proot-distro
proot-distro install ${config.distro}
` : `
echo "[*] Installing PRoot Distro (Ubuntu 24.04)..."
pkg install -y proot-distro
proot-distro install ubuntu
`}

echo "[*] Installing Desktop Environment: ${config.de.toUpperCase()}..."
${
  config.de === 'xfce'
    ? 'proot-distro login ubuntu --shared-tmp -- bash -c "apt update && apt install -y xfce4 xfce4-goodies dbus-x11"'
    : config.de === 'lxqt'
    ? 'proot-distro login ubuntu --shared-tmp -- bash -c "apt update && apt install -y lxqt-core openbox dbus-x11"'
    : config.de === 'i3'
    ? 'proot-distro login ubuntu --shared-tmp -- bash -c "apt update && apt install -y i3 i3status dmenu stterm dbus-x11"'
    : 'proot-distro login ubuntu --shared-tmp -- bash -c "apt update && apt install -y openbox tint2 obconf dbus-x11"'
}

${config.installWine ? `
echo "[*] Installing Box64 and Wine for Windows app compatibility..."
proot-distro login ubuntu --shared-tmp -- bash -c "apt install -y box64 wine64"
` : ''}

echo "[+] Termux Desktop setup complete!"
echo "[+] Start your desktop using: tx11start"
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateBashScript());
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2500);
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Hero Banner */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-slate-900 via-slate-900 to-emerald-950/40 p-8 border border-slate-800 shadow-xl">
        <div className="absolute -right-12 -bottom-12 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute right-32 top-4 w-48 h-48 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 max-w-3xl">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-mono mb-4">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Interactive Setup Builder</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Build Your Custom Termux Desktop
          </h1>
          <p className="mt-3 text-slate-300 text-sm sm:text-base leading-relaxed">
            Customize your Linux desktop environment for Android. Select your preferred display server, window manager, hardware acceleration driver, and PRoot distro to generate an instant automated setup script.
          </p>
        </div>
      </div>

      {/* Configuration Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Options Form (Left 2 cols) */}
        <div className="lg:col-span-2 space-y-6">
          {/* Desktop Environment */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
            <h3 className="text-sm font-semibold text-white uppercase tracking-wider flex items-center space-x-2 mb-4">
              <Box className="w-4 h-4 text-emerald-400" />
              <span>1. Choose Desktop Environment</span>
            </h3>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {[
                { id: 'xfce', name: 'XFCE4 Desktop', desc: 'Feature-rich, highly stable, full panel & window manager (Recommended)' },
                { id: 'lxqt', name: 'LXQt Lightweight', desc: 'Modern Qt-based lightweight desktop with low memory footprint' },
                { id: 'i3', name: 'i3 Tiling Window Manager', desc: 'Fast, keyboard-driven tiling window manager for power users' },
                { id: 'openbox', name: 'Openbox Minimal', desc: 'Extremely lightweight stacking window manager with tint2 panel' },
              ].map((item) => (
                <div
                  key={item.id}
                  onClick={() => setConfig({ ...config, de: item.id as DesktopEnvironment })}
                  className={`p-4 rounded-xl border cursor-pointer transition-all ${
                    config.de === item.id
                      ? 'bg-emerald-500/10 border-emerald-500/50 shadow-md shadow-emerald-500/5'
                      : 'bg-slate-950/40 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-sm text-white">{item.name}</span>
                    {config.de === item.id && <Check className="w-4 h-4 text-emerald-400" />}
                  </div>
                  <p className="mt-1 text-xs text-slate-400">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Display Server & Protocol */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
            <h3 className="text-sm font-semibold text-white uppercase tracking-wider flex items-center space-x-2 mb-4">
              <Terminal className="w-4 h-4 text-cyan-400" />
              <span>2. Choose Display Protocol</span>
            </h3>
            
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {[
                { id: 'termux-x11', name: 'Termux-X11', desc: 'Native Android X11 app with hardware acceleration & smooth audio' },
                { id: 'vnc', name: 'TigerVNC', desc: 'Universal VNC viewer protocol compatible with any VNC client app' },
                { id: 'proot-distro', name: 'PRoot Direct', desc: 'Headless or direct framebuffer container session' },
              ].map((item) => (
                <div
                  key={item.id}
                  onClick={() => setConfig({ ...config, protocol: item.id as DisplayProtocol })}
                  className={`p-4 rounded-xl border cursor-pointer transition-all ${
                    config.protocol === item.id
                      ? 'bg-cyan-500/10 border-cyan-500/50 shadow-md shadow-cyan-500/5'
                      : 'bg-slate-950/40 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-xs text-white">{item.name}</span>
                    {config.protocol === item.id && <Check className="w-3.5 h-3.5 text-cyan-400" />}
                  </div>
                  <p className="mt-1 text-xs text-slate-400 line-clamp-2">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Hardware Acceleration & Distro */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
              <h3 className="text-sm font-semibold text-white uppercase tracking-wider flex items-center space-x-2 mb-4">
                <Cpu className="w-4 h-4 text-purple-400" />
                <span>3. Hardware Acceleration</span>
              </h3>
              
              <div className="space-y-3">
                {[
                  { id: 'adreno', name: 'Adreno GPU (Turnip + Zink)', desc: 'For Snapdragon processors (60fps Vulkan)' },
                  { id: 'mali', name: 'Mali GPU (Panfrost / Generic)', desc: 'For MediaTek and Exynos processors' },
                  { id: 'none', name: 'No Acceleration (Software)', desc: 'Standard Mesa software rendering' },
                ].map((item) => (
                  <div
                    key={item.id}
                    onClick={() => setConfig({ ...config, hwa: item.id as HardwareAccel })}
                    className={`p-3 rounded-xl border cursor-pointer transition-all ${
                      config.hwa === item.id
                        ? 'bg-purple-500/10 border-purple-500/50'
                        : 'bg-slate-950/40 border-slate-800 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-xs text-white">{item.name}</span>
                      {config.hwa === item.id && <Check className="w-3.5 h-3.5 text-purple-400" />}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
              <h3 className="text-sm font-semibold text-white uppercase tracking-wider flex items-center space-x-2 mb-4">
                <HardDrive className="w-4 h-4 text-blue-400" />
                <span>4. PRoot Linux Distro</span>
              </h3>
              
              <div className="space-y-3">
                {[
                  { id: 'ubuntu', name: 'Ubuntu 24.04 LTS', desc: 'Most popular, vast software repositories' },
                  { id: 'debian', name: 'Debian 12 (Bookworm)', desc: 'Extremely lightweight and rock-solid' },
                  { id: 'arch', name: 'Arch Linux', desc: 'Rolling release with AUR support' },
                ].map((item) => (
                  <div
                    key={item.id}
                    onClick={() => setConfig({ ...config, distro: item.id as DistroType })}
                    className={`p-3 rounded-xl border cursor-pointer transition-all ${
                      config.distro === item.id
                        ? 'bg-blue-500/10 border-blue-500/50'
                        : 'bg-slate-950/40 border-slate-800 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-xs text-white">{item.name}</span>
                      {config.distro === item.id && <Check className="w-3.5 h-3.5 text-blue-400" />}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Optional Add-ons */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
            <h3 className="text-sm font-semibold text-white uppercase tracking-wider flex items-center space-x-2 mb-4">
              <Shield className="w-4 h-4 text-amber-400" />
              <span>5. Optional Add-ons</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <label className="flex items-center space-x-3 p-3 rounded-xl bg-slate-950/40 border border-slate-800 cursor-pointer hover:border-slate-700">
                <input
                  type="checkbox"
                  checked={config.installWine}
                  onChange={(e) => setConfig({ ...config, installWine: e.target.checked })}
                  className="rounded bg-slate-800 border-slate-700 text-emerald-500 focus:ring-emerald-500 h-4 w-4"
                />
                <div>
                  <span className="text-xs font-medium text-white block">Box64 & Wine 64-bit</span>
                  <span className="text-[11px] text-slate-400">Run Windows .exe apps on Termux</span>
                </div>
              </label>

              <label className="flex items-center space-x-3 p-3 rounded-xl bg-slate-950/40 border border-slate-800 cursor-pointer hover:border-slate-700">
                <input
                  type="checkbox"
                  checked={config.audio}
                  onChange={(e) => setConfig({ ...config, audio: e.target.checked })}
                  className="rounded bg-slate-800 border-slate-700 text-emerald-500 focus:ring-emerald-500 h-4 w-4"
                />
                <div>
                  <span className="text-xs font-medium text-white block">PulseAudio Forwarding</span>
                  <span className="text-[11px] text-slate-400">Enable Linux desktop audio on Android</span>
                </div>
              </label>
            </div>
          </div>
        </div>

        {/* Generated Script Preview (Right 1 col) */}
        <div className="space-y-6">
          <div className="bg-slate-950 border border-slate-800 rounded-2xl shadow-xl sticky top-24 overflow-hidden flex flex-col h-[650px]">
            {/* Terminal Header */}
            <div className="flex items-center justify-between px-4 py-3 bg-slate-900 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <div className="w-3 h-3 rounded-full bg-red-500/80" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                <div className="w-3 h-3 rounded-full bg-emerald-500/80" />
                <span className="ml-2 text-xs font-mono text-slate-400">setup-termux-desktop.sh</span>
              </div>
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center space-x-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono transition"
                >
                  {copiedScript ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3 text-cyan-400" />}
                  <span>{copiedScript ? 'Copied!' : 'Copy'}</span>
                </button>
                <button
                  onClick={onExportScript}
                  className="flex items-center space-x-1 px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-mono transition"
                >
                  <Download className="w-3 h-3" />
                  <span>Download</span>
                </button>
              </div>
            </div>

            {/* Code Output */}
            <div className="p-4 overflow-y-auto flex-1 font-mono text-xs text-emerald-400/90 bg-slate-950 leading-relaxed selection:bg-emerald-500 selection:text-black">
              <pre>{generateBashScript()}</pre>
            </div>

            {/* Footer Summary */}
            <div className="p-4 bg-slate-900/80 border-t border-slate-800 flex items-center justify-between">
              <div className="text-xs text-slate-400">
                <span className="text-white font-medium">Ready to run</span> in Termux app
              </div>
              <button
                onClick={handleCopy}
                className="px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white text-xs font-semibold shadow-lg shadow-emerald-600/20 transition flex items-center space-x-1.5"
              >
                <Terminal className="w-3.5 h-3.5" />
                <span>Copy Setup Command</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
